version: '3.8'

services:
  rag-kb:
    build: .
    container_name: rag-kb
    ports:
      - "7860:7860"
    volumes:
      - rag-kb-data:/app/chroma
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rag-kb-data:
    driver: local
