name: Sync to HuggingFace Spaces

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hf-spaces:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Add HuggingFace Space as remote
      run: |
        git remote add hf-space https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/kachaje/llm-kb
        
    - name: Push to HuggingFace Space
      run: |
        git push --force hf-space main
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
