name: Sync to HuggingFace Spaces

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hf-spaces:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Install HuggingFace CLI
      run: |
        pip install huggingface_hub[cli]
        
    - name: Login to HuggingFace
      run: |
        huggingface-cli login --token ${{ secrets.HF_TOKEN }}
        
    - name: Clone and sync to HuggingFace Space
      run: |
        git clone https://huggingface.co/spaces/kachaje/llm-kb temp-space
        rsync -av --exclude=temp-space . temp-space/
        cd temp-space
        # Set the correct remote URL for HuggingFace
        git remote set-url origin https://huggingface.co/spaces/kachaje/llm-kb
        git add .
        git commit -m "Sync from GitHub - $(date)" || true
        git push origin main